'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.269
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CertificateGenerator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _resume() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_resume", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property address_book() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("address_book", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property alarm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alarm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property attachment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attachment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bar_chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar_chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BeanButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BeanButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BeanLabel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BeanLabel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BeanTextField() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BeanTextField", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_COLORS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_COLORS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_CONNECTION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_CONNECTION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_CONNECTIONPOOL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_CONNECTIONPOOL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_CONNINCOMPAT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_CONNINCOMPAT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_CONVTABLES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_CONVTABLES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_DEVICES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_DEVICES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_DISPLAYICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_DISPLAYICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_DRVMAP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_DRVMAP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_FILETRANSFER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_FILETRANSFER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_FTPBICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_FTPBICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_HLLAPI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_HLLAPI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_HOSTPRINTER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_HOSTPRINTER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_HOTSPOTS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_HOTSPOTS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_JWTICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_JWTICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_KEYBOARD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_KEYBOARD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_KEYPAD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_KEYPAD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_LOGON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_LOGON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_MACRO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_MACRO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_MENU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_MENU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_MOUSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_MOUSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_OTHERS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_OTHERS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_PRINTERICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_PRINTERICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_PRTRED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_PRTRED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_SCHEME() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_SCHEME", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_SESSGROUP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_SESSGROUP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_SESSION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_SESSION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BIG_TOOLBAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BIG_TOOLBAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property briefcase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("briefcase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property brush() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brush", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check_mark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check_mark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clientes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clientes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cloudy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cloudy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cloudy_sunny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cloudy_sunny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comment_bubble() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comment_bubble", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property danger_sign() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("danger_sign", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property digital_camera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("digital_camera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DISPLAYSEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISPLAYSEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eject() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eject", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property envelope() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("envelope", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property envelope_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("envelope_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exclamanation_mark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exclamanation_mark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fast_forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fast_forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property file() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forbidden_sign() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forbidden_sign", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ftlist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ftlist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ftrecv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ftrecv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ftsend() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ftsend", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property house() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("house", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ipad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ipad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iphone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iphone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joystick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joystick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JTERM_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JTERM_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JWTIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JWTIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property left_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lightbulb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lightbulb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LOGO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property magnifier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magnifier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property md_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("md_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property md_info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("md_info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property md_quest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("md_quest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property md_warn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("md_warn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monitor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monitor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mouse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mouse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property movie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("movie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property newdir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newdir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property news() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("news", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property padlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("padlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property padlock_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("padlock_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PENCIL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PENCIL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property phone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property phone_book() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phone_book", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property phone_ringing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phone_ringing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pie_chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pie_chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property placemark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("placemark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prevfold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prevfold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property question_mark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("question_mark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QuickSearch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuickSearch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rainy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rainy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property record() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("record", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property recycle_bin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("recycle_bin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rewind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rewind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property right_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rss() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rss", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shopping_cart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shopping_cart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skip_backward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skip_backward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skip_forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skip_forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_COLOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_COLOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_CONNECTIONPOOL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_CONNECTIONPOOL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_CONNECTIONS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_CONNECTIONS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_CONVTABLES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_CONVTABLES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_DEVICES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_DEVICES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_DIR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_DIR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_DISPLAYDISABLED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_DISPLAYDISABLED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_DISPLAYICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_DISPLAYICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_DRVMAP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_DRVMAP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_FILETRANSFER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_FILETRANSFER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_FILETRANSFERICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_FILETRANSFERICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_FILETRANSFERICONDISABLED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_FILETRANSFERICONDISABLED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_HLLAPI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_HLLAPI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_HOSTPRIN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_HOSTPRIN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_HOTSPOT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_HOTSPOT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_JWTDISABLED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_JWTDISABLED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_JWTICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_JWTICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_KEYBOARD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_KEYBOARD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_KEYPAD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_KEYPAD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_LOGON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_LOGON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_MACRO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_MACRO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_MEMBER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_MEMBER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_MENU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_MENU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_MOUSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_MOUSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_MYCOMP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_MYCOMP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_OTHERS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_OTHERS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_PRINTERDISABLED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_PRINTERDISABLED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_PRINTERICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_PRINTERICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_PRTRED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_PRTRED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_SCHEMES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_SCHEMES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_SCHOTHER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_SCHOTHER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_SCHOWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_SCHOWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_SESSION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_SESSION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SMALL_TOOLBAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMALL_TOOLBAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smart_phone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smart_phone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sunny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sunny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property support() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("support", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_ABOUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_ABOUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_ADD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_ADD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_CLEAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_CLEAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_CLOSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_CLOSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_CONNECT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_CONNECT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_CONNECTED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_CONNECTED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_COPY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_COPY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_COPYAPPEND() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_COPYAPPEND", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_CUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_CUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_EXITALL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_EXITALL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_FKEY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_FKEY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_HELP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_HELP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_INFO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_INFO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_KEYPAD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_KEYPAD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_KSEQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_KSEQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_MACRO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_MACRO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_MACROPAUSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_MACROPAUSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_MACROPLAY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_MACROPLAY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_MACRORECORD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_MACRORECORD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_MACROSTOP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_MACROSTOP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_OPEN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_OPEN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_OPTIONS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_OPTIONS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_PASTE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_PASTE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_PRINT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_PRINT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_PRINT_FLUSH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_PRINT_FLUSH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_PROJECTNEW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_PROJECTNEW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_RECEIVEFROMHOST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_RECEIVEFROMHOST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_SAVESESSION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_SAVESESSION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_SECURE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_SECURE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_SELECTALL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_SELECTALL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_SENDTOHOST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_SENDTOHOST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_SHOWLAUNCHER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_SHOWLAUNCHER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_SWITCHTO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_SWITCHTO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_UNMARK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_UNMARK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_BIG_URL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_BIG_URL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_ABOUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_ABOUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_CLEAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_CLEAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_CLOSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_CLOSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_CONNECT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_CONNECT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_CONNECTED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_CONNECTED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_COPY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_COPY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_COPYAPPEND() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_COPYAPPEND", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_CUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_CUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_EXITALL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_EXITALL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_FKEY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_FKEY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_HELP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_HELP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_INFO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_INFO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_KEYPAD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_KEYPAD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_KSEQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_KSEQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_MACRO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_MACRO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_MACROPAUSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_MACROPAUSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_MACROPLAY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_MACROPLAY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_MACRORECORD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_MACRORECORD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_MACROSTOP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_MACROSTOP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_OPEN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_OPEN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_OPTIONS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_OPTIONS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_PASTE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_PASTE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_PRINT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_PRINT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_PRINT_FLUSH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_PRINT_FLUSH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_RECEIVEFROMHOST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_RECEIVEFROMHOST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_SAVESESSION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_SAVESESSION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_SECURE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_SECURE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_SELECTALL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_SELECTALL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_SENDTOHOST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_SENDTOHOST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_SHOWLAUNCHER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_SHOWLAUNCHER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_SWITCHTO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_SWITCHTO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_UNMARK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_UNMARK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TB_SMALL_URL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TB_SMALL_URL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property umbrella() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("umbrella", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property up_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("up_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property video() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("video", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property webcam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("webcam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
